# Generated by Django 5.0 on 2023-12-13 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqlapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Код клиента',
            new_name='clientid',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='ИНН',
            new_name='inn',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='СНИЛС',
            new_name='snils',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='Код договора',
            new_name='contractid',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='Дата заключения договора',
            new_name='dateofupbringing',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='Услуга',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='Код партнёра',
            new_name='partnerid',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Дата рождения',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Имя',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Отчество',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Фамилия',
            new_name='mname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Паспортные данные',
            new_name='passport',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='Номер телефона',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='Стаж (в годах)',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='Должность',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='Код сотрудника',
            new_name='workerid',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Электронная почта',
        ),
        migrations.AddField(
            model_name='partner',
            name='extra_info',
            field=models.CharField(default='extrainfo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='naming',
            field=models.CharField(default='genericname', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='worktime_beginning',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='worktime_end',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
