# Generated by Django 5.0 on 2023-12-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqlapp', '0003_rename_fname_person_middle_name_remove_person_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partnerid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='workerid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
